name: location_example
description: Demonstrates how to use the location plugin.

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  location:
    path: ../

dev_dependencies:
  flutter_driver:
    sdk: flutter

flutter:
  uses-material-design: true
